// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {email} from '../models';
import {storage} from '../models';
import {task} from '../models';

export function AddOutlookAccounts(arg1:string):Promise<Record<string, any>>;

export function AddProxyEntry(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function CancelUpdate():Promise<Record<string, any>>;

export function CheckLicense():Promise<Record<string, any>>;

export function CheckUpdate():Promise<Record<string, any>>;

export function ClearOutlookAccounts():Promise<Record<string, any>>;

export function ClearRegisteredOutlookAccounts():Promise<Record<string, any>>;

export function DeleteOutlookAccount(arg1:string):Promise<Record<string, any>>;

export function DeleteOutlookAccounts(arg1:Array<string>):Promise<Record<string, any>>;

export function DeleteProxyEntry(arg1:string):Promise<Record<string, any>>;

export function DetectClashProxy(arg1:string,arg2:proxy.ClashConfig):Promise<proxy.Info>;

export function DetectEmailProxy(arg1:string):Promise<proxy.Info>;

export function DetectProxy(arg1:string):Promise<proxy.Info>;

export function DownloadUpdate():Promise<Record<string, any>>;

export function ExportAccountPoolJSON():Promise<Record<string, any>>;

export function GetClashConfig():Promise<proxy.ClashConfig>;

export function GetClashProxy():Promise<string>;

export function GetCloudMailConfigs():Promise<Array<email.CloudMailConfig>>;

export function GetDataDir():Promise<string>;

export function GetEmailProxy():Promise<string>;

export function GetKillSwitchEnabled():Promise<boolean>;

export function GetKiroRSConfig():Promise<Record<string, any>>;

export function GetLanguage():Promise<string>;

export function GetLicenseInfo():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetMoeMailConfigs():Promise<Array<email.MoeMailConfig>>;

export function GetOSLanguage():Promise<string>;

export function GetOutlookAccounts():Promise<Array<Record<string, any>>>;

export function GetOutlookGraphRegistrationEmailMode():Promise<string>;

export function GetOutlookScope():Promise<string>;

export function GetOverview():Promise<Record<string, any>>;

export function GetProxy():Promise<string>;

export function GetProxyMode():Promise<string>;

export function GetRegistrationConfig():Promise<storage.RegistrationConfig>;

export function GetResultOutputDir():Promise<string>;

export function GetSoundEnabled():Promise<boolean>;

export function GetStatus():Promise<Record<string, any>>;

export function GetSubscriptionLink(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetSubscriptionPlans(arg1:string):Promise<Record<string, any>>;

export function GetTaskStatus():Promise<Record<string, any>>;

export function GetVerifyModelsEnabled():Promise<boolean>;

export function ImportAccountPoolJSON(arg1:string):Promise<Record<string, any>>;

export function ImportOutlookFile(arg1:string):Promise<Record<string, any>>;

export function ListAccountPool():Promise<Record<string, any>>;

export function ListProxyPool():Promise<Array<proxy.PoolEntry>>;

export function LoadOutputAccounts():Promise<Record<string, any>>;

export function LogoutLicense():Promise<Record<string, any>>;

export function OpenURL(arg1:string):Promise<void>;

export function ResetDataDir():Promise<Record<string, any>>;

export function ResetEmailProxy():Promise<Record<string, any>>;

export function ResetFingerprintCache():Promise<Record<string, any>>;

export function ResetOutlookAccountStatuses():Promise<Record<string, any>>;

export function ResetOutlookAccountStatusesByEmails(arg1:Array<string>):Promise<Record<string, any>>;

export function ResetProxy():Promise<Record<string, any>>;

export function ResetResultOutputDir():Promise<Record<string, any>>;

export function SaveCloudMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SaveMoeMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function SelectOutlookFile():Promise<string>;

export function SetClashConfig(arg1:proxy.ClashConfig):Promise<Record<string, any>>;

export function SetClashProxy(arg1:string):Promise<Record<string, any>>;

export function SetDataDir(arg1:string):Promise<Record<string, any>>;

export function SetEmailProxy(arg1:string):Promise<Record<string, any>>;

export function SetKillSwitchEnabled(arg1:boolean):Promise<Record<string, any>>;

export function SetKiroRSConfig(arg1:string,arg2:string,arg3:boolean):Promise<Record<string, any>>;

export function SetLanguage(arg1:string):Promise<Record<string, any>>;

export function SetOutlookGraphRegistrationEmailMode(arg1:string):Promise<Record<string, any>>;

export function SetOutlookScope(arg1:string):Promise<Record<string, any>>;

export function SetProxy(arg1:string):Promise<Record<string, any>>;

export function SetProxyMode(arg1:string):Promise<Record<string, any>>;

export function SetRegistrationConfig(arg1:storage.RegistrationConfig):Promise<Record<string, any>>;

export function SetResultOutputDir(arg1:string):Promise<Record<string, any>>;

export function SetSoundEnabled(arg1:boolean):Promise<Record<string, any>>;

export function SetVerifyModelsEnabled(arg1:boolean):Promise<Record<string, any>>;

export function StartTask(arg1:task.StartTaskRequest):Promise<Record<string, any>>;

export function StopTask():Promise<Record<string, any>>;

export function SyncAccountPoolToKiroRS(arg1:string):Promise<Record<string, any>>;

export function TestCloudMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestKiroRSConnection(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TestMoeMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestProxyEntry(arg1:string):Promise<proxy.Info>;

export function UpdateProxyEntry(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<Record<string, any>>;

export function VerifyLicense(arg1:string):Promise<Record<string, any>>;
