// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOutlookAccounts(arg1) {
  return window['go']['main']['App']['AddOutlookAccounts'](arg1);
}

export function AddProxyEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProxyEntry'](arg1, arg2, arg3);
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearOutlookAccounts() {
  return window['go']['main']['App']['ClearOutlookAccounts']();
}

export function ClearRegisteredOutlookAccounts() {
  return window['go']['main']['App']['ClearRegisteredOutlookAccounts']();
}

export function DeleteOutlookAccount(arg1) {
  return window['go']['main']['App']['DeleteOutlookAccount'](arg1);
}

export function DeleteOutlookAccounts(arg1) {
  return window['go']['main']['App']['DeleteOutlookAccounts'](arg1);
}

export function DeleteProxyEntry(arg1) {
  return window['go']['main']['App']['DeleteProxyEntry'](arg1);
}

export function DetectClashProxy(arg1, arg2) {
  return window['go']['main']['App']['DetectClashProxy'](arg1, arg2);
}

export function DetectEmailProxy(arg1) {
  return window['go']['main']['App']['DetectEmailProxy'](arg1);
}

export function DetectProxy(arg1) {
  return window['go']['main']['App']['DetectProxy'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExportAccountPoolJSON() {
  return window['go']['main']['App']['ExportAccountPoolJSON']();
}

export function GetClashConfig() {
  return window['go']['main']['App']['GetClashConfig']();
}

export function GetClashProxy() {
  return window['go']['main']['App']['GetClashProxy']();
}

export function GetCloudMailConfigs() {
  return window['go']['main']['App']['GetCloudMailConfigs']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetEmailProxy() {
  return window['go']['main']['App']['GetEmailProxy']();
}

export function GetKillSwitchEnabled() {
  return window['go']['main']['App']['GetKillSwitchEnabled']();
}

export function GetKiroRSConfig() {
  return window['go']['main']['App']['GetKiroRSConfig']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMoeMailConfigs() {
  return window['go']['main']['App']['GetMoeMailConfigs']();
}

export function GetOSLanguage() {
  return window['go']['main']['App']['GetOSLanguage']();
}

export function GetOutlookAccounts() {
  return window['go']['main']['App']['GetOutlookAccounts']();
}

export function GetOutlookScope() {
  return window['go']['main']['App']['GetOutlookScope']();
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetPageStayConfig() {
  return window['go']['main']['App']['GetPageStayConfig']();
}

export function GetProxy() {
  return window['go']['main']['App']['GetProxy']();
}

export function GetProxyMode() {
  return window['go']['main']['App']['GetProxyMode']();
}

export function GetRegistrationConfig() {
  return window['go']['main']['App']['GetRegistrationConfig']();
}

export function GetResultOutputDir() {
  return window['go']['main']['App']['GetResultOutputDir']();
}

export function GetSoundEnabled() {
  return window['go']['main']['App']['GetSoundEnabled']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptionLink(arg1, arg2) {
  return window['go']['main']['App']['GetSubscriptionLink'](arg1, arg2);
}

export function GetSubscriptionPlans(arg1) {
  return window['go']['main']['App']['GetSubscriptionPlans'](arg1);
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function GetVerifyModelsEnabled() {
  return window['go']['main']['App']['GetVerifyModelsEnabled']();
}

export function ImportAccountPoolJSON(arg1) {
  return window['go']['main']['App']['ImportAccountPoolJSON'](arg1);
}

export function ImportOutlookFile(arg1) {
  return window['go']['main']['App']['ImportOutlookFile'](arg1);
}

export function ListAccountPool() {
  return window['go']['main']['App']['ListAccountPool']();
}

export function ListProxyPool() {
  return window['go']['main']['App']['ListProxyPool']();
}

export function LoadOutputAccounts() {
  return window['go']['main']['App']['LoadOutputAccounts']();
}

export function LogoutLicense() {
  return window['go']['main']['App']['LogoutLicense']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ResetDataDir() {
  return window['go']['main']['App']['ResetDataDir']();
}

export function ResetEmailProxy() {
  return window['go']['main']['App']['ResetEmailProxy']();
}

export function ResetFingerprintCache() {
  return window['go']['main']['App']['ResetFingerprintCache']();
}

export function ResetOutlookAccountStatuses() {
  return window['go']['main']['App']['ResetOutlookAccountStatuses']();
}

export function ResetProxy() {
  return window['go']['main']['App']['ResetProxy']();
}

export function ResetResultOutputDir() {
  return window['go']['main']['App']['ResetResultOutputDir']();
}

export function SaveCloudMailConfigs(arg1) {
  return window['go']['main']['App']['SaveCloudMailConfigs'](arg1);
}

export function SaveMoeMailConfigs(arg1) {
  return window['go']['main']['App']['SaveMoeMailConfigs'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectOutlookFile() {
  return window['go']['main']['App']['SelectOutlookFile']();
}

export function SetClashConfig(arg1) {
  return window['go']['main']['App']['SetClashConfig'](arg1);
}

export function SetClashProxy(arg1) {
  return window['go']['main']['App']['SetClashProxy'](arg1);
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function SetEmailProxy(arg1) {
  return window['go']['main']['App']['SetEmailProxy'](arg1);
}

export function SetKillSwitchEnabled(arg1) {
  return window['go']['main']['App']['SetKillSwitchEnabled'](arg1);
}

export function SetKiroRSConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetKiroRSConfig'](arg1, arg2, arg3);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetOutlookScope(arg1) {
  return window['go']['main']['App']['SetOutlookScope'](arg1);
}

export function SetPageStayConfig(arg1) {
  return window['go']['main']['App']['SetPageStayConfig'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['main']['App']['SetProxy'](arg1);
}

export function SetProxyMode(arg1) {
  return window['go']['main']['App']['SetProxyMode'](arg1);
}

export function SetRegistrationConfig(arg1) {
  return window['go']['main']['App']['SetRegistrationConfig'](arg1);
}

export function SetResultOutputDir(arg1) {
  return window['go']['main']['App']['SetResultOutputDir'](arg1);
}

export function SetSoundEnabled(arg1) {
  return window['go']['main']['App']['SetSoundEnabled'](arg1);
}

export function SetVerifyModelsEnabled(arg1) {
  return window['go']['main']['App']['SetVerifyModelsEnabled'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function SyncAccountPoolToKiroRS(arg1) {
  return window['go']['main']['App']['SyncAccountPoolToKiroRS'](arg1);
}

export function TestCloudMailConnection(arg1) {
  return window['go']['main']['App']['TestCloudMailConnection'](arg1);
}

export function TestKiroRSConnection(arg1, arg2) {
  return window['go']['main']['App']['TestKiroRSConnection'](arg1, arg2);
}

export function TestMoeMailConnection(arg1) {
  return window['go']['main']['App']['TestMoeMailConnection'](arg1);
}

export function TestProxyEntry(arg1) {
  return window['go']['main']['App']['TestProxyEntry'](arg1);
}

export function UpdateProxyEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProxyEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function VerifyLicense(arg1) {
  return window['go']['main']['App']['VerifyLicense'](arg1);
}
